apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: postgres-service
  namespace: dev
spec:
  ports:
  - name: pg-port
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
status:
  loadBalancer: {}