apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-service
  name: backend-service
  namespace: dev
spec:
  ports:
  - name: http
    nodePort: 31000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: backend
  type: NodePort
status:
  loadBalancer: {}